version: "3.8"

services:
  app:
    build: .
    # command: sh -c "python main.py"
    env_file:
      - .env
    ports:
      - ${PUBLIC_PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/code
    restart: unless-stopped

  db:
    image: mongo:7.0.5
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
volumes:
  mongodb_data:
