version: "3.8"

services:
  app:
    build: .
    command: sh -c "streamlit run app.py"
    ports:
      - 8051:8051
    env_file: .env
    environment: # phần này ta định nghĩa ở file .env nhé
      - API_URL=${API_URL}
    volumes:
      - .:/app
