apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-dep
  labels:
    app.kubernetes.io/name: fsa-kubernetes-demo
spec:
  selector:
    matchLabels:
      app: fastapi-dep
  template:
    metadata:
      labels:
        app: fastapi-dep
    spec:
      containers:
      - name: fastapi-dep
        image: asia-southeast1-docker.pkg.dev/fsa-kubernets/fsa-kubernetes-demo/fsa-backend
        env:
          - name: PUBLIC_PORT
            value: "8000"  # Replace with your desired port
          - name: PORT
            value: "8000"  # Replace with your FastAPI app's port
          - name: DB_HOST
            value: "mongodb"  # Corrected MongoDB service name
          - name: DB_PORT
            value: "27017"
          - name: DB_NAME
            value: "my_db"
        ports:
        - containerPort: 8000
          name: http-fastapi
        volumeMounts:
        - name: data
          mountPath: /app/storage
            
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: demo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-dep
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http-fastapi
  type: LoadBalancer

# ---

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mongodb
# spec:
#   serviceName: "mongodb"
#   replicas: 3
#   selector:
#     matchLabels:
#       app: mongodb
#   template:
#     metadata:
#       labels:
#         app: mongodb
#     spec:
#       containers:
#       - name: mongodb
#         image: mongo:latest
#         ports:
#         - containerPort: 27017
#         volumeMounts:
#         - name: mongo-data
#           mountPath: /data/db
#   volumeClaimTemplates:
#   - metadata:
#       name: mongo-data
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       resources:
#         requests:
#           storage: 2Gi

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mongodb-dep
#   labels:
#     app: mongodb-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongodb-app
#   template:
#     metadata:
#       labels:
#         app: mongodb-app
#     spec:
#       containers:
#       - name: mongo
#         image: mongo:7.0.5
#         ports:
#         - containerPort: 27017
#         volumeMounts:
#         - name: demo-pvc
#           mountPath: /data/db

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: demo-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: "2Gi"
